In [52]:
import torch
from torch.nn import Linear
import math

In [65]:
l = Linear(in_features=2, out_features=1)
a = torch.tensor([1, 2], dtype=torch.float32)
res = math.pi * l(a)
print(res)

tensor([3.2151], grad_fn=<MulBackward0>)


In [54]:
res.backward()

In [68]:
torch.tensor([2]).isclose(torch.tensor([3]))

tensor([False])

In [78]:
def angular_loss(ang_dist):
    if ang_dist < math.pi:
        return ang_dist
    elif ang_dist < 2*math.pi:
        return 2*math.pi - ang_dist
    elif ang_dist.isclose(2 * torch.tensor([torch.pi])):
        return 2*math.pi - ang_dist
    else:   
        raise ValueError(f"ang_dist must be in [0, 2*pi), got {ang_dist}")

In [81]:
angular_loss(torch.tensor([2*math.pi]))

tensor([0.])