In [624]:
import torch

In [625]:
torch.zeros(0, 1)

tensor([], size=(0, 1))

In [626]:
batch = 1000
torch.tensor([batch], dtype=torch.int64)

tensor([1000])

In [627]:
logs = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype=torch.float32)
logs.exp()

tensor([2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02, 4.0343e+02,
        1.0966e+03, 2.9810e+03, 8.1031e+03, 2.2026e+04])

In [628]:
import torch

# Initial dimensions
n_symm = 2
n = 3
batch0 = 4

# Create a tensor representing samples before symmetry and reshaping
# For simplicity, let's fill it with integers to easily track transformations
samples_initial = torch.arange(n_symm * n * batch0).reshape(n_symm, n, batch0)


# Apply a dummy symmetry operation (for the sake of example, let's just return the tensor as is)
def symmetry(samples):
    # In a real scenario, this function would apply some symmetry transformation
    return samples, torch.zeros((n_symm, batch0))  # Returning a dummy phase tensor


samples, phase = symmetry(samples_initial)

# Reshape according to the code snippet
samples = samples.transpose(0, 1).reshape(n, -1)  # (n, n_symm*batch0)

print("Example `samples` tensor after applying symmetry and reshaping:")
print(samples)

Example `samples` tensor after applying symmetry and reshaping:
tensor([[ 0,  1,  2,  3, 12, 13, 14, 15],
        [ 4,  5,  6,  7, 16, 17, 18, 19],
        [ 8,  9, 10, 11, 20, 21, 22, 23]])


In [629]:
import torch
import torch.nn as nn
from torch.nn import TransformerEncoder, TransformerEncoderLayer

In [630]:
embedding_size = 32
n_head = 8
n_hid = embedding_size
n_layers = 8
dropout = 0
minibatch = 10000

In [631]:
encoder_layers = TransformerEncoderLayer(embedding_size, n_head, n_hid, dropout)
transformer_encoder = TransformerEncoder(encoder_layers, n_layers)

/opt/homebrew/anaconda3/envs/scratchgpt/lib/python3.12/site-packages/torch/nn/modules/transformer.py:306: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(f"enable_nested_tensor is True, but self.use_nested_tensor is False because {why_not_sparsity_fast_path}")


In [632]:
transformer_encoder_input = torch.randn(minibatch, 10, embedding_size)

## What Does sample() Do?

In [633]:
from torch.distributions.binomial import Binomial

In [634]:
batch = 10
samples = torch.zeros(0, 1)
sample_count = torch.tensor([batch], dtype=torch.int64)
probs = torch.tensor([0.5], dtype=torch.float32)  # P(s_1  | J) = 0.5

print("batch:", batch)
print("samples:", samples)
print("sample_count:", sample_count)

batch: 10
samples: tensor([], size=(0, 1))
sample_count: tensor([10])


In [712]:
distribution = Binomial(total_count=sample_count, probs=probs)
zero_count = distribution.sample()
one_count = sample_count - zero_count
sample_count = torch.cat((zero_count, one_count), dim=0)
print("sample_count before mask:\n", sample_count)
mask = sample_count > 0
reverse_mask = ~mask
batch = samples.shape[1]
samples = torch.cat(
    [
        torch.cat([samples, torch.zeros(1, batch)], dim=0),
        torch.cat([samples, torch.ones(1, batch)], dim=0),
    ],
    dim=1,
)
print("samples before mask:\n", samples)
masked_samples = samples.T[mask].T
print("samples to mask away:\n", samples.T[reverse_mask].T)
samples = samples.T[mask].T
sample_count = sample_count[mask]

sample_count before mask:
 tensor([1., 0., 1., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 0., 3.])
samples before mask:
 tensor([[0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1.],
        [0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1.],
        [0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1.]])
samples to mask away:
 tensor([[0., 1., 0., 0., 1., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0.],
        [1., 1., 1., 0., 0., 0., 1., 0.],
        [0., 0., 1., 1., 1., 1., 1., 1.],
        [1., 0., 1., 0., 1., 1., 1., 1.],
        [0., 1., 1., 0., 0., 0., 0., 1.],
        [0

 - Columns are sampled sequences. sample() will first generate
these, ensuring they are unique. 
- It uses a probability 
distribution to sample, but does not use the probability distribution in the construction of the unique sequences.
- The information about the sampled spins from the probability distribution is stored in sample_count, which is returned from sample()
- samples is also returned from sample 

In [713]:
# This is whether the zero or one addition is actually possible.
# If not, we eliminate the whole row.
mask

tensor([ True, False,  True, False,  True,  True,  True, False, False,  True,
        False,  True, False, False, False,  True])

In [714]:
samples

tensor([[0., 1., 1., 0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 1., 1., 1.],
        [1., 1., 1., 1., 1., 0., 0., 1.],
        [0., 1., 1., 1., 1., 1., 0., 1.],
        [0., 0., 0., 0., 1., 0., 1., 1.],
        [0., 0., 1., 1., 1., 0., 0., 1.],
        [0., 0., 0., 0., 0., 1., 1., 1.]])

In [715]:
sample_count

tensor([1., 1., 1., 1., 1., 1., 1., 3.])

In [716]:
# Boolean masks:
example = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype=torch.float32)
example_mask = example > 5
example[example_mask]

tensor([ 6.,  7.,  8.,  9., 10.])

In [717]:
import numpy as np

In [718]:
system_sizes = np.arange(10, 41, 2).reshape(-1, 1)
system_sizes

array([[10],
       [12],
       [14],
       [16],
       [18],
       [20],
       [22],
       [24],
       [26],
       [28],
       [30],
       [32],
       [34],
       [36],
       [38],
       [40]])

In [719]:
system_sizes.shape

(16, 1)

In [720]:
from torch.nn import functional as F

In [721]:
import torch

# Input tensor
x = torch.tensor([1.0, 2.0, -3.0])

# Compute softmax
softmax = torch.softmax(torch.tensor([1.0, 2.0, 3.0]), dim=0)

# Print the result
print(softmax)

tensor([0.0900, 0.2447, 0.6652])


In [722]:

print(torch.softmax(torch.tensor([1.0, 20.0, -3.0]), dim=0))
print(torch.softmax(torch.tensor([1.0, 20.0, -3.0]) / 4, dim=0))

tensor([5.6028e-09, 1.0000e+00, 1.0262e-10])
tensor([0.0086, 0.9883, 0.0031])
