In [54]:
from Hamiltonian import Ising

In [55]:
i = Ising(8, periodic=False)

Ising provides the familiar Ising model Hamiltonian, stored as a sparse matrix:

In [44]:
print(i.full_H(param=-1))

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2304 stored elements and shape (256, 256)>
  Coords	Values
  (0, 0)	-7.0
  (0, 1)	-1.0
  (0, 2)	-1.0
  (0, 4)	-1.0
  (0, 8)	-1.0
  (0, 16)	-1.0
  (0, 32)	-1.0
  (0, 64)	-1.0
  (0, 128)	-1.0
  (1, 0)	-1.0
  (1, 1)	-5.0
  (1, 3)	-1.0
  (1, 5)	-1.0
  (1, 9)	-1.0
  (1, 17)	-1.0
  (1, 33)	-1.0
  (1, 65)	-1.0
  (1, 129)	-1.0
  (2, 0)	-1.0
  (2, 2)	-3.0
  (2, 3)	-1.0
  (2, 6)	-1.0
  (2, 10)	-1.0
  (2, 18)	-1.0
  (2, 34)	-1.0
  :	:
  (253, 221)	-1.0
  (253, 237)	-1.0
  (253, 245)	-1.0
  (253, 249)	-1.0
  (253, 252)	-1.0
  (253, 253)	-3.0
  (253, 255)	-1.0
  (254, 126)	-1.0
  (254, 190)	-1.0
  (254, 222)	-1.0
  (254, 238)	-1.0
  (254, 246)	-1.0
  (254, 250)	-1.0
  (254, 252)	-1.0
  (254, 254)	-5.0
  (254, 255)	-1.0
  (255, 127)	-1.0
  (255, 191)	-1.0
  (255, 223)	-1.0
  (255, 239)	-1.0
  (255, 247)	-1.0
  (255, 251)	-1.0
  (255, 253)	-1.0
  (255, 254)	-1.0
  (255, 255)	-7.0


In [45]:
print(i.full_H(param=-1).toarray())

[[-7. -1. -1. ...  0.  0.  0.]
 [-1. -5.  0. ...  0.  0.  0.]
 [-1.  0. -3. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ... -3.  0. -1.]
 [ 0.  0.  0. ...  0. -5. -1.]
 [ 0.  0.  0. ... -1. -1. -7.]]


First goal: calculate ground states in a memoized manner (i.e., store ground states as they are calculated. If a ground state has been calculated, do not recalculate it). 

One ground state for every set of parameters (i.e., for every \vec J).

In [46]:
import numpy as np

In [47]:
system_sizes = np.arange(10, 41, 2).reshape(-1, 1)
print(system_sizes)

[[10]
 [12]
 [14]
 [16]
 [18]
 [20]
 [22]
 [24]
 [26]
 [28]
 [30]
 [32]
 [34]
 [36]
 [38]
 [40]]


In [48]:
print(system_sizes.shape)

(16, 1)


In [49]:
i.calc_E_ground()

-9.837951447459417

In [50]:
import torch

In [51]:
ground_e, ground = i.calc_ground(param=torch.Tensor([-1]))
print(ground)

[0.34092676 0.17341612 0.10926527 0.135509   0.10152125 0.06035918
 0.07547059 0.12080312 0.09956416 0.05324485 0.03674014 0.05080382
 0.06637165 0.04510004 0.06556163 0.11668931 0.09956416 0.05182483
 0.03350286 0.04360443 0.03372261 0.02140749 0.02845482 0.04848858
 0.06448121 0.03671324 0.02724627 0.04142772 0.05693603 0.04207108
 0.06442415 0.12080312 0.10152125 0.05233717 0.03335008 0.04249269
 0.03165931 0.01946203 0.02501058 0.04142772 0.03372261 0.01867455
 0.01335858 0.01952487 0.02556718 0.01835489 0.02751094 0.05080382
 0.06637165 0.03575832 0.02383751 0.03296985 0.02556718 0.01737731
 0.02427367 0.04360443 0.05693603 0.03404907 0.02638059 0.04249269
 0.05782542 0.04490157 0.07029894 0.135509   0.10926527 0.05608446
 0.0355667  0.04490157 0.03335008 0.02024501 0.02571568 0.04207108
 0.03350286 0.01827741 0.01285256 0.01835489 0.02383751 0.01674098
 0.02476005 0.04510004 0.03674014 0.01953553 0.01285256 0.01737731
 0.01335858 0.00885459 0.01213012 0.02140749 0.02724627 0.0160

In [52]:
ground

array([0.34092676, 0.17341612, 0.10926527, 0.135509  , 0.10152125,
       0.06035918, 0.07547059, 0.12080312, 0.09956416, 0.05324485,
       0.03674014, 0.05080382, 0.06637165, 0.04510004, 0.06556163,
       0.11668931, 0.09956416, 0.05182483, 0.03350286, 0.04360443,
       0.03372261, 0.02140749, 0.02845482, 0.04848858, 0.06448121,
       0.03671324, 0.02724627, 0.04142772, 0.05693603, 0.04207108,
       0.06442415, 0.12080312, 0.10152125, 0.05233717, 0.03335008,
       0.04249269, 0.03165931, 0.01946203, 0.02501058, 0.04142772,
       0.03372261, 0.01867455, 0.01335858, 0.01952487, 0.02556718,
       0.01835489, 0.02751094, 0.05080382, 0.06637165, 0.03575832,
       0.02383751, 0.03296985, 0.02556718, 0.01737731, 0.02427367,
       0.04360443, 0.05693603, 0.03404907, 0.02638059, 0.04249269,
       0.05782542, 0.04490157, 0.07029894, 0.135509  , 0.10926527,
       0.05608446, 0.0355667 , 0.04490157, 0.03335008, 0.02024501,
       0.02571568, 0.04207108, 0.03350286, 0.01827741, 0.01285

In [57]:
basis = i.generate_basis()
print(basis)
print("Shape: ", basis.shape)

[[0 0 0 ... 1 1 1]
 [0 0 0 ... 1 1 1]
 [0 0 0 ... 1 1 1]
 ...
 [0 0 0 ... 1 1 1]
 [0 0 1 ... 0 1 1]
 [0 1 0 ... 1 0 1]]
Shape:  (8, 256)
