In [2]:
from Hamiltonian import Ising

In [3]:
i = Ising(8, periodic=False)

/Users/spandan/Projects/old/tqs/Hamiltonian_utils.py:44: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  system_size = torch.tensor(system_size, dtype=torch.int64).reshape(-1)


Ising provides the familiar Ising model Hamiltonian, stored as a sparse matrix:

In [4]:
print(i.full_H(param=-1))

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2304 stored elements and shape (256, 256)>
  Coords	Values
  (0, 0)	-7.0
  (0, 1)	-1.0
  (0, 2)	-1.0
  (0, 4)	-1.0
  (0, 8)	-1.0
  (0, 16)	-1.0
  (0, 32)	-1.0
  (0, 64)	-1.0
  (0, 128)	-1.0
  (1, 0)	-1.0
  (1, 1)	-5.0
  (1, 3)	-1.0
  (1, 5)	-1.0
  (1, 9)	-1.0
  (1, 17)	-1.0
  (1, 33)	-1.0
  (1, 65)	-1.0
  (1, 129)	-1.0
  (2, 0)	-1.0
  (2, 2)	-3.0
  (2, 3)	-1.0
  (2, 6)	-1.0
  (2, 10)	-1.0
  (2, 18)	-1.0
  (2, 34)	-1.0
  :	:
  (253, 221)	-1.0
  (253, 237)	-1.0
  (253, 245)	-1.0
  (253, 249)	-1.0
  (253, 252)	-1.0
  (253, 253)	-3.0
  (253, 255)	-1.0
  (254, 126)	-1.0
  (254, 190)	-1.0
  (254, 222)	-1.0
  (254, 238)	-1.0
  (254, 246)	-1.0
  (254, 250)	-1.0
  (254, 252)	-1.0
  (254, 254)	-5.0
  (254, 255)	-1.0
  (255, 127)	-1.0
  (255, 191)	-1.0
  (255, 223)	-1.0
  (255, 239)	-1.0
  (255, 247)	-1.0
  (255, 251)	-1.0
  (255, 253)	-1.0
  (255, 254)	-1.0
  (255, 255)	-7.0


In [5]:
print(i.full_H(param=-1).toarray())

[[-7. -1. -1. ...  0.  0.  0.]
 [-1. -5.  0. ...  0.  0.  0.]
 [-1.  0. -3. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ... -3.  0. -1.]
 [ 0.  0.  0. ...  0. -5. -1.]
 [ 0.  0.  0. ... -1. -1. -7.]]


First goal: calculate ground states in a memoized manner (i.e., store ground states as they are calculated. If a ground state has been calculated, do not recalculate it). 

One ground state for every set of parameters (i.e., for every \vec J).

In [2]:
import numpy as np

In [3]:
system_sizes = np.arange(10, 41, 2).reshape(-1, 1)