## Running the Supervised Optimizer

From start to finish, on pretrained weights


In [1]:
import torch
import numpy as np
import os
from Hamiltonian import Ising
from model import TransformerModel
from optimizer_supervised import Optimizer

In [2]:
system_sizes = np.arange(4, 10, 2).reshape(-1, 1)
Hamiltonians = [Ising(size, periodic=True) for size in system_sizes]
param_dim = Hamiltonians[0].param_dim
embedding_size = 32
n_head = 8
n_hid = embedding_size
n_layers = 8
dropout = 0
minibatch = 10000
param_range = None
point_of_interest = None
use_SR = False

print("Sizes:\n", system_sizes)
print("Hamiltonians:", Hamiltonians)
print("Dimensions of parameter space:", param_dim)
print("Number of units in a feedforward layer:", n_hid)

Sizes:
 [[ 4]
 [ 6]
 [ 8]
 [10]
 [12]
 [14]
 [16]]
Hamiltonians: [<Hamiltonian.Ising object at 0x7b90cff5d610>, <Hamiltonian.Ising object at 0x7b90cfd903e0>, <Hamiltonian.Ising object at 0x7b90d2300f50>, <Hamiltonian.Ising object at 0x7b90d1f715b0>, <Hamiltonian.Ising object at 0x7b90cff7b0e0>, <Hamiltonian.Ising object at 0x7b92841efa10>, <Hamiltonian.Ising object at 0x7b92841ed0a0>]
Dimensions of parameter space: 1
Number of units in a feedforward layer: 32


/home/spandan/Projects/tqs/Hamiltonian_utils.py:44: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  system_size = torch.tensor(system_size, dtype=torch.int64).reshape(-1)


In [3]:
testmodel = TransformerModel(
    system_sizes,
    param_dim,
    embedding_size,
    n_head,
    n_hid,
    n_layers,
    dropout=dropout,
    minibatch=minibatch,
)

results_dir = "results"
paper_checkpoint_name = "ckpt_100000_Ising_32_8_8_0.ckpt"
paper_checkpoint_path = os.path.join(results_dir, paper_checkpoint_name)
checkpoint = torch.load(paper_checkpoint_path)
testmodel.load_state_dict(checkpoint)

/home/spandan/anaconda3/envs/tqs2/lib/python3.12/site-packages/torch/nn/modules/transformer.py:306: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer was not TransformerEncoderLayer
  warnings.warn(f"enable_nested_tensor is True, but self.use_nested_tensor is False because {why_not_sparsity_fast_path}")


<All keys matched successfully>

In [4]:
opt = Optimizer(testmodel, Hamiltonians, point_of_interest=point_of_interest)

In [5]:
epochs = 1000
param_range = torch.tensor([[0.5, 1.5]])
param_step = torch.tensor([0.05])

opt.train(epochs=epochs, param_range=param_range, param_step=param_step, start_iter=0)

System size: tensor([4]), Hamiltonian time: 0.3105621337890625, Last loss: 0.038856737315654755
System size: tensor([6]), Hamiltonian time: 0.5233709812164307, Last loss: 0.008414474315941334
System size: tensor([8]), Hamiltonian time: 0.8384876251220703, Last loss: 0.0019499781774356961
System size: tensor([10]), Hamiltonian time: 1.7963738441467285, Last loss: 0.0004881069762632251


KeyboardInterrupt: 

In [ ]:
H = Hamiltonians[2]
param = torch.tensor([0.8000])
ground_energy, psi_true = H.calc_ground(param)
psi_true

tensor([-0.4928,  0.1036,  0.1036,  ...,  0.1036,  0.1036, -0.4928],
       dtype=torch.float64)

In [ ]:
basis = H.generate_basis()
basis.shape

torch.Size([14, 16384])

In [ ]:
from model_utils import compute_psi

testmodel.set_param(system_size=H.system_size, param=param)
log_amp, log_phase = compute_psi(testmodel, basis, H.symmetry, check_duplicate=True)
print(log_amp)
print(log_phase)

tensor([-2.0506, -3.7310, -4.7868,  ..., -4.7868, -3.7310, -2.0506],
       grad_fn=<LogBackward0>)
tensor([-6.0865,  0.1709,  0.1618,  ...,  0.1618,  0.1709, -6.0865],
       grad_fn=<MulBackward0>)
